version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /Users/adityatodi/Work/relative/v2/logging/grpc-example/logs:/grpc-example/logs
    ports:
      - "9000"
  app-2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /Users/adityatodi/Work/relative/v2/logging/grpc-example/logs:/grpc-example/logs
    ports:
      - "9000"